number_first = int(input("First number: "))
number_second = int(input("Second number: "))
print('Add', number_first + number_second)
print('Subtract', number_first - number_second)
print('Multiply', number_first * number_second)
print('Divide', round((number_first / number_second), 2))
print('Exponentiation', number_first ** number_second)
